# Generated by Django 5.0.4 on 2024-05-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("especie", models.CharField(max_length=255)),
                ("sexo", models.CharField(max_length=255)),
                ("idade", models.CharField(max_length=255)),
                ("cor", models.CharField(max_length=255)),
                ("castrado", models.CharField(max_length=255)),
            ],
        ),
    ]
